TheatreWebApp/Models/Booking.cs
using System;
using System.Collections.Generic;

namespace TheatreWebApp.Models
{
    public partial class Booking
    {
        public int Id { get; set; }
        public int ShowId { get; set; }
        public string UserId { get; set; }
        public int SeatTypeId { get; set; }
        public int NumberOfSeats { get; set; }
        public double TotalPrice { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual SeatType SeatType { get; set; }
        public virtual Show Show { get; set; }
    }
}

TheatreWebApp/ViewModels/BookingViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheatreWebApp.Models;

namespace TheatreWebApp.ViewModels
{
    public class BookingViewModel
    {


        TheatreDbContext db = new TheatreDbContext();

        public int NumberOfSeats { get; set; }

        public int SeatType { get; set; }
        public DateTime DateTime { get; set; }

        public Show Show { get; set; }

        public SelectList SeatTypes
        {
            get
            {
                return new SelectList(db.SeatTypes, "Id", "Type");
            }

        }

        public SelectList Productions
        {
            get
            {
                return new SelectList(db.Productions, "Id", "Title");
            }
        }

        public IEnumerable<Show> Shows
        {
            get
            {
                return db.Shows;
            }
        }

    }
}

TheatreWebApp/ViewModels/CalendarViewModel.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using TheatreWebApp.Repository;

namespace TheatreWebApp.ViewModels
{
    public class CalendarViewModel
    {
        public CalendarViewModel(ITheatreRepository repository)
        {
            var shows = repository.GetShows();
            var _events = shows.Select(show => new CalendarEventViewModel
            {
                id = show.Id, title = show.Production.Title, start = show.DateTime, allDay = false, 
                url = "/productions/details/" + show.ProductionId + 
                "?date="+show.DateTime.ToString("g")
            }).ToList();

            events = _events;
            editable = false;
        }
        public bool editable { get; set; }
        public IEnumerable<CalendarEventViewModel> events { get; set; }
    }
}

TheatreWebApp/ViewModels/CheckoutViewModel.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data.Odbc;
using System.Drawing;
using System.Linq;
using System.Net.Sockets;
using System.Web;
using System.Web.Mvc;
using TheatreWebApp.Models;
using TheatreWebApp.Repository;

namespace TheatreWebApp.ViewModels
{
    public class CheckoutViewModel
    {
        TheatreRepository _repository = new TheatreRepository();
        public Show Show { get; set; }
        public Production Production { get; set; }
        public int NumberOfTickets { get; set; }
        public SeatType SeatType { get; set; }
        public CardDetails CardDetails { get; set; }

        [Required(ErrorMessage = "Please enter your email address")]
        [DisplayName("Email Address")]       
        public string EmailAddress { get; set; }

        [Required(ErrorMessage = "Please enter your mobile number")]
        [DisplayName("Mobile Number")]
        public string PhoneNumber { get; set; }

        public bool UserIsLoggedIn { get; set; }

        [DisplayName("Save Details")]
        public bool SaveDetails { get; set; }

        [DisplayName("Use Existing Details")]
        public bool UseExistingDetails { get; set; }

        public string TicketPrice
        {
            get
            {
                return String.Format("€{0:0.00}", (Production.BasePrice * SeatType.PriceMultiplier));
            }
        }

        public string TotalPrice
        {
            get
            {
                return String.Format("€{0:0.00}", (Production.BasePrice * SeatType.PriceMultiplier * NumberOfTickets));
            }
        }

        public IEnumerable<SelectListItem> CardTypes
        {
            get
            {
                var repository = new TheatreRepository();
                IList<CardType> cardTypes = _repository.GetCardTypes();
                IEnumerable <SelectListItem> selectList =
                from c in cardTypes
                select new SelectListItem
                {
                    Text = c.Company,
                    Value = c.Id.ToString()
                };
                return selectList;
            }
        }

        public IEnumerable<SelectListItem> Months
        {
            get
            {
                IList<string> monthsList = _repository.GetMonthsList();
                IEnumerable<SelectListItem> selectList =
                from c in monthsList
                select new SelectListItem
                {
                    Text = c,
                    Value = c
                };
                return selectList;
            }
        }

        public IEnumerable<SelectListItem> Years
        {
            get
            {
                IList<string> yearsList = _repository.GetYearsList();
                IEnumerable<SelectListItem> selectList =
                from c in yearsList
                select new SelectListItem
                {
                    Text = c,
                    Value = c
                };
                return selectList;
            }
        }
    }
}

TheatreWebApp/ViewModels/PurchaseViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheatreWebApp.Models;
using TheatreWebApp.Repository;

namespace TheatreWebApp.ViewModels
{
    public class PurchaseViewModel
    {
        private ITheatreRepository _repository;

        public PurchaseViewModel()
        {
            _repository = new TheatreRepository();
        }

        public PurchaseViewModel(ITheatreRepository repository)
        {
            _repository = repository;
        }


        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Please select a showing")]
        public int SelectedShowId { get; set; }

        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Please select a seat type")]
        public int SelectedSeatTypeId { get; set; }
        
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Please select a production")]
        public int SelectedProductionId { get; set; }
        [Required]
        public string SelectedTime { get; set; }
        [Required]
        public DateTime SelectedDate { get; set; }

        public IEnumerable<SelectListItem> Shows
        {
            get
            {
                var shows = _repository.GetShows().Select(s => new SelectListItem
                {
                    Value = s.Id.ToString(CultureInfo.InvariantCulture),
                    Text = s.DateTime.ToLongDateString() + " " + s.DateTime.ToShortTimeString()
                });
                return DefaultShowItem.Concat(shows); 
            }
        }

        public IEnumerable<SelectListItem> Productions
        {
            get
            {
                var productions = _repository.GetProductions().Select(s => new SelectListItem
                {
                    Value = s.Id.ToString(CultureInfo.InvariantCulture),
                    Text = s.Title
                });
                return DefaultProductionItem.Concat(productions); 
            }
        }

        public IEnumerable<SelectListItem> SeatTypes
        {
            get
            {
                var seatTypes = _repository.GetSeatTypes().Select(s => new SelectListItem
                {
                    Value = s.Id.ToString(CultureInfo.InvariantCulture),
                    Text = s.Type
                });
                return DefaultSeatTypeItem.Concat(seatTypes); 
            }
        }

        public Show Show { get; set; }

        public SeatType Seat { get; set; }

        public int NumberOfTickets { get; set; }

        public IEnumerable<SelectListItem> DefaultSeatTypeItem
        {
            get
            {
                return Enumerable.Repeat(new SelectListItem
                {
                    Value = "-1",
                    Text = "Select Seat Type..."
                }, count: 1);
            }
        }

        public IEnumerable<SelectListItem> DefaultProductionItem
        {
            get
            {
                return Enumerable.Repeat(new SelectListItem
                {
                    Value = "-1",
                    Text = "Select Production..."
                }, count: 1);
            }
        }

        public IEnumerable<SelectListItem> DefaultShowItem
        {
            get
            {
                return Enumerable.Repeat(new SelectListItem
                {
                    Value = "-1",
                    Text = "Select Show..."
                }, count: 1);
            }
        }
    }
}

TheatreWebApp/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using TheatreWebApp.Models;
using TheatreWebApp.Repository;
using TheatreWebApp.ViewModels;

namespace TheatreWebApp.Controllers
{
    public class BookingController : Controller
    {

        //
        // GET: /Booking/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Booking/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Booking/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        // GET: /Booking/Calendar
        public ActionResult Calendar()
        {
            var eventsJson = JsonConvert.SerializeObject(new CalendarViewModel(new TheatreRepository()));
            ViewBag.Events = eventsJson;
            return View();
        }


        //[Authorize]
        public ActionResult Purchase(int? id, string date)
        {
            var model = new PurchaseViewModel(new TheatreRepository());
            if(id != null && id > 0) model.SelectedProductionId = (int) id;
            if (date != null)
            {
                var selectedDate = DateTime.Parse(date);
                ViewBag.Date = new DateDTO()
                {
                    Year = selectedDate.Year,
                    Month = selectedDate.Month,
                    Day = selectedDate.Day,
                    Time = selectedDate.ToShortTimeString()
                };
            }

            return View(model);
        }



        //Action result for ajax call
        [HttpPost]
        public ActionResult GetProductionsByDate(string date)
        {
            var dateTime = Convert.ToDateTime(date);
            var repository = new TheatreRepository();
            var productions = repository.GetProductionsForDate(dateTime);
            var prodSelectList = new SelectList(productions, "Id", "Title", 0);
            return Json(prodSelectList);
        }

        //Action result for ajax call
        [HttpPost]
        public ActionResult GetShowsForProduction(string date, string productionid)
        {
            var dateTime = Convert.ToDateTime(date);
            var prodId = Int32.Parse(productionid);
            var repository = new TheatreRepository();
            var shows = repository.GetShowsForProduction(dateTime, prodId);
            var prodSelectList = new SelectList(shows, "Id", "ViewTime", 0);
            return Json(prodSelectList);
        }

        //Action result for ajax call
        [HttpPost]
        public ActionResult GetDatesForProduction(string productionid)
        {
            var prodId = Int32.Parse(productionid);
            var repository = new TheatreRepository();
            var dates = repository.GetDatesForProductions(prodId);
            return Json(dates);
        }

        public ActionResult Checkout()
        {
            return RedirectToAction("Purchase");
        }

        //[Authorize]
        [HttpPost]
        public ActionResult Checkout(PurchaseViewModel purchaseViewModel)
        {
            var db = new TheatreDbContext();
            CardDetails existingCardDetails = null;
            var userIsLoggedIn = User.Identity.IsAuthenticated;

            if (userIsLoggedIn)
            {
                var username = User.Identity.Name;
                var userId = db.AspNetUsers.SingleOrDefault(x => x.UserName == username).Id;
                existingCardDetails = db.CardDetails.SingleOrDefault(x => x.UserId == userId);
            }

            var production = db.Productions.Single(p => p.Id == purchaseViewModel.SelectedProductionId);
            var show = db.Shows.Single(s => s.Id == purchaseViewModel.SelectedShowId);
            var seatType = db.SeatTypes.Single(s => s.Id == purchaseViewModel.SelectedSeatTypeId);
            var model = new CheckoutViewModel()
            {
                NumberOfTickets = purchaseViewModel.NumberOfTickets,
                Production = production,
                Show = show,
                SeatType = seatType,
                CardDetails = new CardDetails(),
                UserIsLoggedIn = userIsLoggedIn
            };

            if (existingCardDetails != null)
            {
                model.CardDetails = existingCardDetails;
                model.UseExistingDetails = true;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult ConfirmOrder(CheckoutViewModel model)
        {
            var db = new TheatreDbContext();
            CardDetails existingCardDetails = null;
            string userId = null;
            var userIsLoggedIn = User.Identity.IsAuthenticated;

            if (userIsLoggedIn)
            {
                var username = User.Identity.Name;
                userId = db.AspNetUsers.SingleOrDefault(x => x.UserName == username).Id;
                existingCardDetails = db.CardDetails.SingleOrDefault(x => x.UserId == userId);
            }
            
            if (model.SaveDetails && !userId.IsNullOrEmpty())
            {
                model.CardDetails.CardNumber = ObscureCardNumber(model.CardDetails.CardNumber);

                var cardDetails = new CardDetails()
                {
                    CardNumber = model.CardDetails.CardNumber,
                    CardholdersName = model.CardDetails.CardholdersName,
                    CvnNumber = model.CardDetails.CvnNumber,
                    CardType = model.CardDetails.CardType,
                    ExpMonth = model.CardDetails.ExpMonth,
                    ExpYear = model.CardDetails.ExpYear,
                    UserId = userId
                };
                if (existingCardDetails == null)
                {
                    db.CardDetails.Add(cardDetails);
                    db.SaveChanges();
                }
                else
                {
                    existingCardDetails.CardNumber = model.CardDetails.CardNumber;
                    existingCardDetails.CardholdersName = model.CardDetails.CardholdersName;
                    existingCardDetails.CardType = model.CardDetails.CardType;
                    existingCardDetails.CvnNumber = model.CardDetails.CvnNumber;
                    existingCardDetails.ExpMonth = model.CardDetails.ExpMonth;
                    existingCardDetails.ExpYear = model.CardDetails.ExpYear;
                    db.SaveChanges();
                }
            }
            return View(model);
        }

        private string ObscureCardNumber(string input)
        {
            string result = "****-****-****-";
            var charArray = input.ToCharArray();
            for (int i = 15; i < 19; i++)
            {
                result += charArray.GetValue(i);
            }
            
            return result;
        }
     
    }
}

TheatreWebApp/Views/Booking/Calendar.cshtml
@model  TheatreWebApp.ViewModels.CalendarViewModel

@{
    ViewBag.Title = "title";

}


<div id='calendar'></div>

@section scripts {

    <script>

    $('#calendar').fullCalendar(@Html.Raw(ViewBag.Events));

</script>
}

TheatreWebApp/Views/Booking/Checkout.cshtml
@model TheatreWebApp.ViewModels.CheckoutViewModel

  @{
        ViewBag.Title = "title";
        HtmlHelper.ClientValidationEnabled = true;
        HtmlHelper.UnobtrusiveJavaScriptEnabled = true;
}

        





<div class="container col-md-12" align="center">
    <div class="col-md-12" align="center"><h2>Checkout</h2></div>
    
  
        <div class="well well-lg col-md-4 col-md-offset-1">
            <div class="panel panel-primary">

                <div class="panel-heading">
                    <h3 class="panel-title">Order Confirmation</h3>
                </div>
                <div class="panel-body" align="left">
                    <ul>
                        <li>
                        <strong>Production: </strong> @Model.Production.Title
                        </li>
                        <li>
                            <strong>Author: </strong> @Model.Production.Author
                        </li>
                        <li>
                            <strong>Date: </strong> @Model.Show.DateTime.ToShortDateString()
                        </li>
                        <li>
                            <strong>Time: </strong> @Model.Show.ViewTime
                        </li>
                        <li>
                            <strong>Seat Type: </strong> @Model.SeatType.Type
                        </li>
                        <li>
                            <strong>Ticket Price: </strong> @Model.TicketPrice
                        </li>
                        <li>
                        <strong>Number of Tickets: </strong> @Model.NumberOfTickets

                    </ul>

                    <h3><strong>Total: </strong> @Model.TotalPrice</h3> 
                </div>

            </div>
        </div>
    
    <div class="well well-lg col-md-4 col-md-offset-2">
        @using (Html.BeginForm("ConfirmOrder", "Booking", FormMethod.Post))
        { 
            <div id="paymentDetails" align="left" class="form-group">
                <div class="input-group form-group">
                    @Html.LabelFor(x => x.CardDetails.CardType)
                    @Html.DropDownListFor(x => x.CardDetails.CardType, Model.CardTypes, new { @id="cardType", @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CardDetails.CardType)
                </div>

                <div class="input-group form-group">
                    @Html.LabelFor(x => x.CardDetails.CardNumber)
                    @Html.TextBoxFor(x => x.CardDetails.CardNumber, new { @id = "cardNo", @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CardDetails.CardNumber)
                </div>
            
                <div class="input-group form-group">
                    @Html.LabelFor(x => x.CardDetails.CardholdersName)
                    @Html.TextBoxFor(x => x.CardDetails.CardholdersName, new { @id = "cardholdersName", @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CardDetails.CardholdersName)
                </div>
            
                @if (!Model.UserIsLoggedIn)
                {
                    <div class="input-group form-group">
                        @Html.LabelFor(x => x.EmailAddress)
                        @Html.TextBoxFor(x => x.EmailAddress, new {@id = "email", @class = "form-control"})
                        @Html.ValidationMessageFor(model => model.EmailAddress)
                    </div>

                    <div class="input-group form-group">
                        @Html.LabelFor(x => x.PhoneNumber)
                        @Html.TextBoxFor(x => x.PhoneNumber, new {@id = "phone", @class = "form-control"})
                        @Html.ValidationMessageFor(model => model.PhoneNumber)
                    </div>
                }
            
            

                <div class="input-group form-group" id="cvnDiv">
                    @Html.LabelFor(x => x.CardDetails.CvnNumber)
                    @Html.TextBoxFor(x => x.CardDetails.CvnNumber, new { @id = "cvn", @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CardDetails.CvnNumber)
                </div>
                <div class="form-inline" id="expDateDiv">
                    <div class="input-group form-group">
                        <label>Expiry Month</label>
                        @Html.DropDownListFor(x => x.CardDetails.ExpMonth, Model.Months, new { @id = "ddlMonth", @class = "form-control", size = "1" })
                    </div>
                    <div class="input-group form-group">
                        <label>Expiry Year</label>
                        @Html.DropDownListFor(x => x.CardDetails.ExpYear, Model.Years, new { @id = "ddlYear", @onchange = "refreshMonths(this.value);", @class = "form-control", size = "1" })
                    </div>
                </div>
            
                <div class="input-group form-group" id="saveDetailsDiv">
                    @Html.LabelFor(x => x.SaveDetails)
                    @Html.EditorFor(x => x.SaveDetails, new { @class = "form-control"})
                </div>
            
                @if (Model.CardDetails.CardNumber != null)
                {
                    <div class="input-group form-group">
                        @Html.LabelFor(x => x.UseExistingDetails)
                        @Html.EditorFor(x => x.UseExistingDetails, new { @class = "form-control", @id="useExistingCheckBox" })
                    </div>
                }
                       

            </div>
            
            <div class="" align="center">
                <button type="submit" class="btn btn-default">Pay Now</button>
            </div>
        }
        
        <div id="hiddenFields">
            @Html.HiddenFor(x => x.CardDetails.CardNumber, new {@id="cardNumberHidden"})
            @Html.HiddenFor(x => x.CardDetails.CvnNumber, new { @id = "cvnNumberHidden" })
            @Html.HiddenFor(x => x.CardDetails.CardholdersName, new { @id = "cardholdersNameHidden" })
            @Html.HiddenFor(x => x.CardDetails.ExpYear, new { @id = "expYearHidden" })
            @Html.HiddenFor(x => x.CardDetails.ExpMonth, new { @id = "expMonthHidden" })
            @Html.HiddenFor(x => x.CardDetails.ExpYear, new { @id = "expYearHidden" })
        </div>

    </div>

</div>
    


@section Scripts {
    <script src="~/Scripts/checkoutPageControl.js"></script>

    @if (Model.CardDetails.CardNumber == null)
    {
        <script type="text/javascript">
            $('#saveDetailsDiv').hide();
            initializeExpDropdowns();
        </script>
    }
    else
    {
        <script type="text/javascript">
        //$('#UseExistingDetails').prop({ checked: true });
            togglePaymentFormsVisibility(false);
            setExpDatesToModelValues('@Model.CardDetails.ExpMonth', '@Model.CardDetails.ExpYear');

        </script>
    }


@if (Model.UserIsLoggedIn)
 {
     <script type="text/javascript">
         $('#UseExistingDetails').hide();
         initializeExpDropdowns();
     </script>
 }
 

<script type="text/javascript">
    var foid_ = "825150071";
    var fo = document.createElement('script'); fo.type = 'text/javascript';
    fo.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'f.formisimo.com/tk.js';
    var fs = document.getElementsByTagName('script')[0]; fs.parentNode.insertBefore(fo, fs);
</script>

}


    

TheatreWebApp/Views/Booking/Create.cshtml
@model TheatreWebApp.ViewModels.BookingViewModel

@{
    ViewBag.Title = "Book Tickets";
    Layout = "/Views/Shared/_Layout";
}

<h2>title</h2>
<div class="row">
    <div class="col-md-8">
        <section id="bookingForm">
            @using (Html.BeginForm("Create", "Booking", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
               
            }
        </section>
    </div>

</div>

TheatreWebApp/Views/Booking/Details.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

TheatreWebApp/Views/Booking/Purchase.cshtml
@using TheatreWebApp.Models
@model TheatreWebApp.ViewModels.PurchaseViewModel

@{
    ViewBag.Title = "title";
    int year =0;
    int month =0;
    int day = 0;
    var time = "";
    var dateIsSelected = false;
    if (ViewBag.Date != null)
    {
        year = ((DateDTO) ViewBag.Date).Year;
        month = ((DateDTO) ViewBag.Date).Month;
        day = ((DateDTO) ViewBag.Date).Day;
        time = ((DateDTO) ViewBag.Date).Time;
        dateIsSelected = true;
    }
}

<div class="container col-md-12">

    <div class="col-md-4 col-md-offset-4" align="center"><h2>Purchase Tickets</h2></div>
    
    <div> @Html.HiddenFor(x => x.SelectedProductionId, new { @id = "hiddenProdId" } )</div>
    @if (dateIsSelected)
    {
        <div> <input data-val="true" id="hiddenYear" type="hidden" value="@year" /></div>
        <div> <input data-val="true" id="hiddenMonth" type="hidden" value="@month" /></div>
        <div> <input data-val="true" id="hiddenDay" type="hidden" value="@day" /></div>
        <div> <input data-val="true" id="hiddenTime" type="hidden" value="@time" /></div>
    }

    

    <div class="well well-lg col-md-4 col-md-offset-4" method="POST" action="Checkout">
        @using (Html.BeginForm("Checkout", "Booking", FormMethod.Post))
        {
            @Html.ValidationSummary(true)
            <div class="form-group">
                <label for="purchaseMethod">Choose by Production</label>
                <input type="radio" id="prodRadio" checked="checked" name="purchaseMethod" value="date" style="margin-left: 1em;">
            </div>

            <div class="form-group">
                <label for="purchaseMethod">Choose by Date</label>
                <input type="radio" id="dateRadio" name="purchaseMethod" value="date" style="margin-left: 1em;">
            </div>

            

            <div id="ticketByDate">
                <div class="input-group form-group">
                    @Html.TextBoxFor(model => model.SelectedDate, new
                    {
                        type = "text",
                        @Value = System.DateTime.Now.ToString("ddd, dd MMM yyyy"),
                        @class = "datepicker form-control",
                        @id = "ddlDateCBD",
                        @onchange = "javascript:GetProductions(this.value, $('#ddlProductions'));"
                    })
                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                    @Html.ValidationMessageFor(model => model.SelectedDate)
                </div>

                <div class="form-group">
                    @*<select id="ddlProductions" name="ddlProduction" class="form-control"
                        onchange=" javascript: GetShowsForProduction(this.value, $('#ddlDateCBD'), $('#ddlShow')); "></select>*@
                    @Html.DropDownListFor(m => m.SelectedProductionId, new List<SelectListItem>(), new
                    {
                        @id = "ddlProductions",
                        @class = "form-control",
                        @onchange=" javascript: GetShowsForProduction(this.value, $('#ddlDateCBD'), $('#ddlShow')); "
                    })
                    @Html.ValidationMessageFor(model => model.SelectedProductionId)
                </div>
                <div class="form-group">
                    @*<select id="ddlShow" name="SelectedShowId" class="form-control"></select>*@
                    @Html.DropDownListFor(m => m.SelectedShowId, new List<SelectListItem>(), new{ @id="ddlShow", @class="form-control"})
                    @Html.ValidationMessageFor(model => model.SelectedShowId)
                </div>

            </div>

            <div id="ticketByProduction">

                <div class="form-group">
                    @Html.DropDownListFor(m => m.SelectedProductionId, Model.Productions, new
                    {
                        @class = "form-control",
                        @onchange = "javascript:GetDates(this.value, $('#ddlDateCBP'), $('#ddlShow2'));",
                        @id = "ddlMainProd"
                    })
                    @Html.ValidationMessageFor(m => m.SelectedProductionId)
                </div>

                <div class="input-group form-group">
                    @Html.TextBoxFor(model => model.SelectedDate, new
                    {
                        type = "text",
                        @id = "ddlDateCBP",
                        @Value = System.DateTime.Now.ToString("ddd, dd MMM yyyy"),
                        @class = "datepicker form-control",
                        @onfocus = "javascript: GetShowsForProduction($('#ddlMainProd').val(), $('#ddlDateCBP'), $('#ddlShow2'));"
                    })
                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                    @Html.ValidationMessageFor(model => model.SelectedDate)
                </div>

                <div class="form-group">
                    @Html.DropDownListFor(m => m.SelectedShowId, new List<SelectListItem>(), new { @id = "ddlShow2", @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SelectedShowId)
                </div>


            </div>

            <div>
                @Html.DropDownListFor(m => m.SelectedSeatTypeId, Model.SeatTypes, new {@class = "form-control", @id = "ddlSeatType"})
                @Html.ValidationMessageFor(m => m.SelectedSeatTypeId)
            </div>

            <div class="input-group form-group padtop">
                <label for="numbertickets">Number of Tickets</label>

                @*<input id="numbertickets" value="2" name="NumberOfTickets">*@
                @Html.TextBoxFor(x => x.NumberOfTickets, new{ @value="2", @id="numbertickets"})
                @Html.ValidationMessageFor(m => m.NumberOfTickets)
            </div>




            <div class="" align="center">
                <button type="submit" class="btn btn-default">Purchase</button>
            </div>


        }
    </div>
</div>





@section Scripts {
    <script src="~/Scripts/purchasePageControl.js"></script>
    <script src="~/Scripts/bootstrapValidation.js"></script>
    @*@if (Model.SelectedProductionId > 0)
    {
        <script>
            selectProduction(@Model.SelectedProductionId);
        </script>
    }*@

}